version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: debate-coach-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: debate-coach-ai
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - debate-coach-network

  # Redis Cache (Optional)
  redis:
    image: redis:7.2-alpine
    container_name: debate-coach-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - debate-coach-network

  # Backend API Server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: debate-coach-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/debate-coach-ai?authSource=admin
      REDIS_URL: redis://redis:6379
      CLIENT_URL: http://localhost:3000
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      SARVAM_API_KEY: ${SARVAM_API_KEY}
      SARVAM_API_BASE_URL: https://api.sarvam.ai/v1
      LOG_LEVEL: info
    depends_on:
      - mongodb
      - redis
    volumes:
      - api_logs:/app/logs
    networks:
      - debate-coach-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: debate-coach-client
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
      REACT_APP_SOCKET_URL: http://localhost:3001
    depends_on:
      - api
    networks:
      - debate-coach-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  api_logs:
    driver: local

networks:
  debate-coach-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
