apiVersion: apps/v1
kind: Deployment
metadata:
  name: debate-coach-client
  labels:
    app: debate-coach
    component: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debate-coach
      component: client
  template:
    metadata:
      labels:
        app: debate-coach
        component: client
    spec:
      containers:
      - name: client
        image: debate-coach-client:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debate-coach-server
  labels:
    app: debate-coach
    component: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debate-coach
      component: server
  template:
    metadata:
      labels:
        app: debate-coach
        component: server
    spec:
      containers:
      - name: server
        image: debate-coach-server:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: debate-coach-secrets
              key: mongodb-uri
        - name: SARVAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: debate-coach-secrets
              key: sarvam-api-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: debate-coach-secrets
              key: jwt-secret
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: debate-coach
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debate-coach
      component: database
  template:
    metadata:
      labels:
        app: debate-coach
        component: database
    spec:
      containers:
      - name: mongodb
        image: mongo:5
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: debate-coach-secrets
              key: mongodb-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: debate-coach-secrets
              key: mongodb-password
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi