apiVersion: v1
kind: Service
metadata:
  name: debate-coach-client
  labels:
    app: debate-coach
    component: client
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: debate-coach
    component: client

---
apiVersion: v1
kind: Service
metadata:
  name: debate-coach-server
  labels:
    app: debate-coach
    component: server
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: debate-coach
    component: server

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: debate-coach
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: debate-coach
    component: database

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: debate-coach-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
  - hosts:
    - debate-coach.com
    secretName: debate-coach-tls
  rules:
  - host: debate-coach.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: debate-coach-server
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: debate-coach-client
            port:
              number: 80